[package]
name = "orbit-sim"
version = "0.1.0"
authors = ["HMPerson1 <hmperson1@gmail.com>"]

[dependencies]
cairo-rs = "0.5"
tau = "1.0"
nalgebra = "0.16"

[dependencies.gtk]
version = "0.5"
features = ["v3_22"]
